# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries

### Task 1 of 1.1 Dictionaries ###
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
To create the values, we used the function "np.range". Since the result will be an array, we converted into a list.Then we create two variables: keys (this are strings) and values. Finally, we converted into a dictionary, pairing it with the zip function.

In [3]:
import numpy as np
even_numbers_list=np.array(np.arange(0,2000,2)).tolist()
odd_numbers_list=np.array(np.arange(9001,19001,2)).tolist()

keys = ['even_numbers','odd_numbers']
values = [ even_numbers_list, odd_numbers_list]
dictionary = dict(zip(keys, values))
print(dictionary)

{'even_numbers': [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 41

### Task 2 of 1.1 Dictionaries ###
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
To answered the question, we just applicated the get method.

In [6]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print("Los valores del key 'brand' : " + str(car.get("brand")))

Los valores del key 'brand' : Ford


### Task 3 of 1.1. Dictionaries ###
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
To answered the question, we just applicated the method value method.

In [11]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print("Los valores del diccionario 'car' : " + str(list(car.values())))

Los valores del diccionario 'car' : ['Ford', 'Mustang', 1964]


### Task 4 of 1.1. Dictionaries ###
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [ ]:
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

max_val = max(hr_sleep["january"]["friday"])
print("El valor máximo del key 'friday' en 'january' : " + str(max_val))

### Task 5 of 1.1. Dictionaries ###
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [13]:
# Solución 01: Agregamos el key 'march' teniendo como valor la LISTA que resulta de unir los valores de 'week1' y 'values2'
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]
week1.extend(values2)
week1

hr_sleep["march"] = week1
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': ['monday', 'sunday', [2, 3, 4], 8]}

In [ ]:
# Solución 02: Agregamos el key 'march' teniendo como valor el DICCIONARIO que resulta de unir los valores de 'week1' y 'values2'

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]
march_dict = {week1[i] : values2[i] for i in range(len(week1))}

hr_sleep["march"] = march_dict
hr_sleep

## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [2]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

#### Task 1 of 1.2 Numpy
To acomplissh task 1, we use operator % to indicate that the data should be arranged according to the suggested multiple number, then the operate == assign the position to iniciate the selection of data. With both operators, we can select even number in numpy array "np1" and use indexing to replace them with 100.   

In [3]:
np1[np1%2==0]=100
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

#### Task 2 of 1.2 Numpy
For task 2, we use operator the function np.arange to create numpy array from 0 to 8. Then, with fuction reshape, we trasform the array of 9 numbers (from 0 to 8) to 3 arrays with 3 elements in each array. 

In [37]:
np3 = np.arange(0,9).reshape(3,3)
print(np3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Task 3 of 1.2 Numpy
For task 3, we transform the list Z to a numpy array with function np.array. Then we generate a series of array by the positions suggested. With these objects, we create a matrix through concatenate function.

In [114]:
Z = [1,2,3,4,5,6,7,8,9,10]
z0 = np.array(Z)
z1 = np.arange(z0[0],z0[4])
z2 = np.arange(z0[1],z0[5])
z3 = np.arange(z0[2],z0[6])
z4 = np.arange(z0[3],z0[7])
z5 = np.arange(z0[4],z0[8])
z6 = np.arange(z0[5],z0[9])
z7 = np.arange(7,11)
R = np.concatenate([[z1,z2,z3,z4,z5,z6,z7]])
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

## Task 4 of 1.2 Numpy

In [4]:
# Realizado por Jose Gomez. La información es subida por el usuario de Alexis Flores
# debido a que no se tiene acceso al repositorio

# Insatlación

import numpy as np

# We indicate that we will use a seed to obtain random data but following a fixed sequence.

np.random.seed(0)

# We create a array 3x3x3 with random values from 0 to 1 set with the seed.
a = np.random.random((3, 3, 3)) 

# Display the array 3x3x3
a


array([[[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318, 0.4236548 , 0.64589411],
        [0.43758721, 0.891773  , 0.96366276]],

       [[0.38344152, 0.79172504, 0.52889492],
        [0.56804456, 0.92559664, 0.07103606],
        [0.0871293 , 0.0202184 , 0.83261985]],

       [[0.77815675, 0.87001215, 0.97861834],
        [0.79915856, 0.46147936, 0.78052918],
        [0.11827443, 0.63992102, 0.14335329]]])

#### Task 5 of 1.2 Numpy
Why is false np.nan == np.nan?

In [ ]:
# Task 5 Realizado por Jose Gomez. La información es subida por el usuario de Alexis Flores
# debido a que no se tiene acceso al repositorio

In [5]:
np.nan == np.nan

False

NAN is a non-number that represents an undefined integer value. In most cases, it represents a missing value in a database. Also, NaN is a special floating point value with a float attribute only. So, the false result with the operator == is given because the value (quantity or unit) that the NAN object carries inside is compared. Being an undefined value, comparing both data will turn out to be false since they are not exact values.

In [6]:
d = np.nan
e = np.nan
d is e

True

However, if we use the "is" operator, we get the result TRUE since it compares both objects based on their identity (float is a float is true). Therefore, the "==" operator compares values of objects, while the "is" operator compares objects based on their attribute or identity. The first will return true as long as the value is defined and equal

Reference
Reference 1: https://www.askpython.com/python/examples/nan-in-numpy-and-pandas Reference 2: https://appdividend.com/2022/01/28/np-nan/ Reference 3: https://www.geeksforgeeks.org/difference-between-and-is-operator-in-python/

#### Task 6 of 1.2 Numpy

In [9]:
# Task 6 Realizado por Jose Gomez. La información es subida por el usuario de Alexis Flores
# debido a que no se tiene acceso al repositorio

In [7]:
np.random.seed(0) #we place a seed to fix the randomization
np2 = np.random.normal( 50 , 4, 300) #Generate a matrix with values based on a normal distribution
print (np2) #Display the array

[57.05620938 51.60062883 53.91495194 58.9635728  57.47023196 46.09088848
 53.80035367 49.39457117 49.58712459 51.64239401 50.57617428 55.81709403
 53.0441509  50.48670007 51.77545293 51.33469731 55.97631629 49.17936694
 51.25227081 46.58361704 39.78804074 52.61447438 53.4577448  47.03133992
 59.0790185  44.1825373  50.18303407 49.2512646  56.13111686 55.87743508
 50.6197897  51.51265008 46.44885701 42.07681413 48.6083514  50.62539588
 54.92116272 54.8095194  48.45069273 48.790789   45.80578814 44.31992825
 43.17491924 57.80310158 47.96139127 48.24770279 44.98881856 53.10996142
 43.54440861 49.14903888 46.41813376 51.54760999 47.95677945 45.27747126
 49.88727109 51.71332748 50.26606889 51.20988759 47.46271163 48.54903534
 47.31015821 48.56178735 46.74741487 43.09486959 50.70970457 48.39287626
 43.47920661 51.85112902 46.37080654 50.20778158 52.91636225 50.51593164
 54.55760274 45.06069672 51.60936656 47.26075964 46.5168114  47.68460134
 48.75378987 50.22466137 45.33940064 53.60330595 51

f-string is a string formatting mechanism known as Literal String Interpolation. Based on a prefix f and between quotation marks (" "), it allows to specify between { } the name of a variable showing its value or to execute a sequence of functions and expressions within the string. With this we obtain the result of the mean, standard deviation and variance rounded to a decimal with the function round(). The standard deviation is obtained from the result of the square root of variance with the help of the function sqrt() with argument np.var().

In [8]:
print(f"The mean is {round(np.mean(np2), 1)}, the standard desviation is {round(np.sqrt(np.var(np2)), 1)} and the variance is {round(np.var(np2), 1)} in the array np2.")

The mean is 50.1, the standard desviation is 4.0 and the variance is 16.0 in the array np2.


## 1.3 Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [47]:
# 1. Get 𝜷ˆ(𝑅𝐿𝑆) vector from the equation bellow. Use the q, p1, p2, p3, CT numpies.

# First we import the relevant libraries:

import numpy as np
from math import log
import pandas as pd

In [48]:
# Now we import the dataset considering the proposed name "greene"
greene = pd.read_csv(r"/Users/joselinchavez/Documents/GitHub/Diplomado_PUCP/Lecture_3/christensen_greene_f4.csv")

#In this case we use the path to the folder where the database 
#is stored because it couldn't be taken directly.

In [49]:
#We can check the database
greene.describe()

id    YEAR        COST              Q            PL  \
count  158.000000   158.0  158.000000     158.000000    158.000000   
mean   127.208861  1970.0   53.269962   10469.410759   8001.863228   
std     60.792333     0.0   87.059326   15187.520802   1398.837478   
min      1.000000  1970.0    0.130400       4.000000   5063.490000   
25%     78.500000  1970.0   10.221050    1971.000000   6975.177500   
50%    138.500000  1970.0   25.545400    5645.500000   7890.185000   
75%    178.750000  1970.0   55.315900   12365.750000   8855.230000   
max    218.000000  1970.0  737.408800  115500.000000  13044.000000   

               SL          PK          SK          PF         SF   
count  158.000000  158.000000  158.000000  158.000000  158.000000  
mean     0.138972   71.421063    0.226387   30.745785    0.632355  
std      0.054735   11.977489    0.060836    7.943089    0.083324  
min      0.045900   31.725000    0.092400    9.000000    0.243500  
25%      0.099725   67.605000    0.192550   24.477350    0.590100  
50%      0.123100   74.120000    0.218600   30.657900    0.645000  
75%      0.169800   78.794250    0.252775   36.000000    0.686900  
max      0.329100   92.650000    0.457100   51.463000    0.813600

In [50]:
# We use the provided renaming:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [51]:
# We also took logs of the relevant variables (14 variables 
# without the intercept, independents) and we can give it the same form as 
#requested by proposed equation 

ln_q = np.log(q)
ln2_q = 0.5*np.square(ln_q) # in this case we need the additional 
# square to logarithm

ln_p1 = np.log(p1)
ln_p2 = np.log(p2)
ln_p3 = np.log(p3)

ln_qp1 = np.multiply(ln_q, ln_p1) # in this case we need to multiply
# adittional to logarithm
ln_qp2 = np.multiply(ln_q, ln_p2)
ln_qp3 = np.multiply(ln_q, ln_p3)

ln2_p1 = 0.5*np.square(ln_p1)
ln2_p2 = 0.5*np.square(ln_p2)
ln2_p3 = 0.5*np.square(ln_p3)

ln_p1p2 = np.multiply(ln_p1, ln_p2)
ln_p1p3 = np.multiply(ln_p1, ln_p3)
ln_p2p3 = np.multiply(ln_p2, ln_p3)

In [56]:
# Now we create the intercept with the function ones:
intercept = np.ones((len(q), 1))
#intercept

# Likewise, we take logarithm of the dependent variable:
ln_ct = np.log(ct)
#ln_ct

In [65]:
# We must also create the big X matrix, it must contain the 14 
# variables and the intercept, so we use the function stack for columns

X_big = np.column_stack([intercept, ln_q, ln2_q, ln_qp1, ln_qp2, 
                         ln_qp3, ln_p1, ln_p2, ln_p3, ln2_p1, ln2_p2,
                         ln2_p3, ln_p1p2, ln_p1p3, ln_p2p3])

X_big

array([[ 1.        ,  2.07944154,  2.16203856, ..., 25.53597848,
        36.87257416, 12.06308434],
       [ 1.        ,  6.76734313, 22.89846649, ..., 27.52922179,
        38.14391527, 12.86998372],
       [ 1.        ,  7.25276242, 26.30128135, ..., 33.47177703,
        33.28867699, 13.81021534],
       ...,
       [ 1.        ,  5.96870756, 17.81273497, ..., 32.93311772,
        37.80502354, 16.56284231],
       [ 1.        ,  8.57866451, 36.79674242, ..., 34.23242826,
        39.94379007, 16.26769248],
       [ 1.        ,  9.63036563, 46.3719711 , ..., 28.72378963,
        38.10118094, 13.96783596]])

In [81]:
# To estimate the 𝜷ˆ(𝑅𝐿𝑆) we should introduce the restrictions in a matrix called L 
# (similar to the hint). Actually, we can verify that some betas doesn't exist for the
# third, fourth, and fifth restrictions, so the last constraint is implicitly introduced on these 

L = np.array( ( [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0 ],
                [ 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1 ] ) )

rr = [ 1, 0, 0, 0, 0 ]

print(L)
print(rr)

[[0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 1]]
[1, 0, 0, 0, 0]


In [73]:
# We implementing the total database:
data_smpl = pd.DataFrame(np.column_stack([ln_ct, X_big]), columns = ["ln_ct","intercept", "ln_q", "ln2_q", 
                                                                     "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                                                     "ln_p2", "ln_p3", "ln2_p1", "ln2_p2",
                                                                     "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"])
#data_smpl

In [78]:
# Now we calculate the usual BETA_ols
XTX_inv  = np.linalg.inv(np.dot(np.transpose(X_big), X_big))
BETAS_ols = np.dot(XTX_inv, np.dot(np.transpose(X_big), ln_ct))

#Nevertheless, we need to calculate the RLS estimator expressed as β_RLS = β_OLS + "Restriction Adjustment"
RA_1 = np.dot(XTX_inv, np.transpose(L))
RA_2 = np.linalg.inv(np.linalg.multi_dot([L, XTX_inv, np.transpose(L)]))
RA_3 = np.dot(L, BETAS_ols) - np.array(rr)
RA   = RA_1.dot(RA_2).dot(RA_3)

# With this adjustment component, we can finally calculate the RLS estimator:
BETAS_rls = BETAS_ols - RA
print(pd.DataFrame(BETAS_rls, index = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"]))


                  0
intercept -7.111200
ln_q       0.461368
ln2_q      0.059955
ln_qp1    -0.004354
ln_qp2     0.036778
ln_qp3    -0.032424
ln_p1      0.215566
ln_p2      0.402923
ln_p3      0.381511
ln2_p1    -0.004356
ln2_p2     0.002578
ln2_p3    -0.007651
ln_p1p2   -0.002936
ln_p1p3    0.007292
ln_p2p3    0.000358


In [80]:
# 2. Get the covariance matrix 𝕍ar(𝜷ˆ(𝑅𝐿𝑆))

# To calculate the covariance matrix we create the estimation residuals, 
# then we find the covvar matrix called "VarCov_rls":
ln_ct_fit = np.dot(X_big, BETAS_rls)
e_resid = np.array(ln_ct) - ln_ct_fit

sigma2_rls = np.sum(e_resid**2) / (len(data_smpl.index) - (len(BETAS_rls) - len(rr)))

D_mat = np.identity(len(BETAS_rls)) - RA_1.dot(RA_2).dot(L)
VarCov_rls = sigma2_rls * D_mat.dot(XTX_inv)

print(pd.DataFrame(VarCov_rls, 
                   index = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"], 
                   columns = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"]))

           intercept      ln_q     ln2_q    ln_qp1    ln_qp2    ln_qp3  \
intercept   8.485895 -0.096160  0.000206  0.015677 -0.022104  0.006427   
ln_q       -0.096160  0.016015 -0.000070 -0.002912  0.002270  0.000642   
ln2_q       0.000206 -0.000070  0.000020 -0.000016 -0.000002  0.000019   
ln_qp1      0.015677 -0.002912 -0.000016  0.000585 -0.000363 -0.000222   
ln_qp2     -0.022104  0.002270 -0.000002 -0.000363  0.000654 -0.000291   
ln_qp3      0.006427  0.000642  0.000019 -0.000222 -0.000291  0.000513   
ln_p1      -3.050502  0.012193 -0.000038 -0.001377  0.005099 -0.003722   
ln_p2       1.613544 -0.014739  0.000150  0.001701 -0.006121  0.004419   
ln_p3       1.436958  0.002546 -0.000112 -0.000324  0.001022 -0.000697   
ln2_p1      0.198259  0.000797  0.000012 -0.000240 -0.000166  0.000406   
ln2_p2     -0.045968 -0.001459  0.000031  0.000281  0.000029 -0.000310   
ln2_p3     -0.411072 -0.000658 -0.000048  0.000287  0.000230 -0.000517   
ln_p1p2    -0.281682  0.000002 -0.0000

## 1.4 Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

### Pandas

1. Ejecute el código a continuación, descomente la segunda línea para instalar la biblioteca savReaderWriter. El dict_varlabels tiene las etiquetas de las columnas de rec1.

2. Compruebe si CASEID identifica cada observación de forma única. Sugerencia: utilice el método is_unique.

3. Haga que la columna CASEID sea el índice de su conjunto de datos. Sugerencia: use set_index.

4. Mantenga a las mujeres que tengan entre 15 y 30 años y vivan en áreas urbanas. Sugerencia: use la consulta.

5. Genera una nueva columna con el mes de nacimiento. Solo usa las tres primeras letras. Usa los nombres en inglés de los meses.

In [8]:
# 1.4.1 Instalación preliminar

import pandas as pd
import numpy  as np
!pip install pyreadstat
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/Users/USER/Documents/GitHub/Diplomado_PUCP/Diplomado_PUCP/_data/endes/2019/REC0111.sav" )

with sav.SavHeaderReader( fr"C:/Users/USER/Documents/GitHub/Diplomado_PUCP/Diplomado_PUCP/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [10]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [11]:
pd.DataFrame(rec1)
dfx= pd.DataFrame(rec1)
dfx

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
0         1.0  2019.0  1434.0   4.0  ...       No       No       No  010101   
1         1.0  2019.0  1434.0   1.0  ...       No       No       No  010101   
2         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
3         1.0  2019.0  1434.0   3.0  ...       No       No       No  010101   
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No       No  250401   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No       No  250401   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No       No  250401   

        V022      V005          V190      V191  \
0        3.0  154803.0          Rico  1.234450   
1        3.0  154803.0          Rico  1.234450   
2        3.0  154803.0          Rico  1.295611   
3        3.0  154803.0          Rico  1.295611   
4        3.0  154803.0        Pobrer -0.256431   
...      ...       ...           ...       ...   
38330  249.0  244995.0  El más pobre -1.750187   
38331  249.0  244995.0  El más pobre -1.676861   
38332  249.0  459792.0  El más pobre -1.585333   
38333  249.0  459792.0  El más pobre -1.650159   
38334  249.0  244995.0  El más pobre -1.644720   

                                        mujeres12a49  NCONGLOME  
0                    Mujeres de 15 a 49 años de edad     7065.0  
1      Mujeres de 12 a 14 de edad, nunca embarazadas     7065.0  
2                    Mujeres de 15 a 49 años de edad     7065.0  
3                    Mujeres de 15 a 49 años de edad     7065.0  
4                    Mujeres de 15 a 49 años de edad     7065.0  
...                                              ...        ...  
38330                Mujeres de 15 a 49 años de edad    15783.0  
38331                Mujeres de 15 a 49 años de edad    15783.0  
38332                Mujeres de 15 a 49 años de edad    15783.0  
38333                Mujeres de 15 a 49 años de edad    15783.0  
38334                Mujeres de 15 a 49 años de edad    15783.0  

[38335 rows x 105 columns]

In [ ]:
dict_varlabels

In [12]:
# 1.4.2 Check if CASEID identifies each observation uniquely. Hint: Use is_unique method.
 # Compruebe si CASEID identifica cada observación de forma única. Sugerencia: utilice el método is_unique

In [14]:
# Comprobamos la cantidad de filas que tiene el DataFrame
dfx.shape[0]

38335

In [15]:
np.array(dfx['CASEID'])

array(['      000100201  2', '      000100201  3', '      000102801  2',
       ..., '      325407001  2', '      325407201  2',
       '      325407401  2'], dtype=object)

In [16]:
#Utilizamos el método is_unique, pero previamente convertimos
array= np.array(dfx['CASEID'])
array
series = pd.Series(array)
series
series.is_unique

True

In [17]:
len(dfx['CASEID'].unique().tolist())

38335

In [18]:
# 1.4.3 Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.
# Genera una nueva columna con el mes de nacimiento. Solo usa las tres primeras letras. Usa los nombres en inglés de los meses.

In [25]:
# Con la información preliminar de dict_varlabels, seleccionamos los campos necesarios y cambiamos de nombre.
# V023': 'Dominio de ejemplo - Departamento',
# V024': 'Región',
# V025': 'Tipo de lugar de residencia',
# V012': 'Edad actual - entrevistada',
# V013': 'Edad actual por grupos de 5 años',
# V102': 'Tipo de lugar de residencia',


dfx1=dfx[["V012","V013","V023","V024","V025","mujeres12a49"]]
dfx1.rename({"V012":"Edad actual","V013":"Edad actual por grupos de 5 años",
             "V023":"Departamento","V024":"Región","V025":"Tipo Residencia","mujeres12a49":"Mujeres"},axis="columns")

Edad actual Edad actual por grupos de 5 años Departamento    Región  \
0             33.0          De 30 a 34 años de edad     Amazonas  Amazonas   
1             12.0          De 12 a 14 años de edad     Amazonas  Amazonas   
2             36.0          De 35 a 39 años de edad     Amazonas  Amazonas   
3             49.0          De 45 a 49 años de edad     Amazonas  Amazonas   
4             28.0          De 25 a 29 años de edad     Amazonas  Amazonas   
...            ...                              ...          ...       ...   
38330         48.0          De 45 a 49 años de edad      Ucayali   Ucayali   
38331         31.0          De 30 a 34 años de edad      Ucayali   Ucayali   
38332         46.0          De 45 a 49 años de edad      Ucayali   Ucayali   
38333         25.0          De 25 a 29 años de edad      Ucayali   Ucayali   
38334         23.0          De 20 a 24 años de edad      Ucayali   Ucayali   

      Tipo Residencia                                        Mujeres  
0              Urbano                Mujeres de 15 a 49 años de edad  
1              Urbano  Mujeres de 12 a 14 de edad, nunca embarazadas  
2              Urbano                Mujeres de 15 a 49 años de edad  
3              Urbano                Mujeres de 15 a 49 años de edad  
4              Urbano                Mujeres de 15 a 49 años de edad  
...               ...                                            ...  
38330           Rural                Mujeres de 15 a 49 años de edad  
38331           Rural                Mujeres de 15 a 49 años de edad  
38332           Rural                Mujeres de 15 a 49 años de edad  
38333           Rural                Mujeres de 15 a 49 años de edad  
38334           Rural                Mujeres de 15 a 49 años de edad  

[38335 rows x 6 columns]

In [26]:
# Con la información seleccionada, procedemos a hacer las funciones condicionales. 
 #Luego creamos una tabla con los campos requeridos del caso. 

Lugar_r= dfx[(dfx["V012"]>=15) & (dfx["V012"]<=30) & (dfx["V025"]=="Urbano")]
Lugar_r[["V023","V024","V025","V012","V013"]]

V023      V024    V025  V012                     V013
4      Amazonas  Amazonas  Urbano  28.0  De 25 a 29 años de edad
5      Amazonas  Amazonas  Urbano  30.0  De 30 a 34 años de edad
8      Amazonas  Amazonas  Urbano  18.0  De 15 a 19 años de edad
9      Amazonas  Amazonas  Urbano  23.0  De 20 a 24 años de edad
12     Amazonas  Amazonas  Urbano  28.0  De 25 a 29 años de edad
...         ...       ...     ...   ...                      ...
38162   Ucayali   Ucayali  Urbano  29.0  De 25 a 29 años de edad
38163   Ucayali   Ucayali  Urbano  20.0  De 20 a 24 años de edad
38164   Ucayali   Ucayali  Urbano  27.0  De 25 a 29 años de edad
38165   Ucayali   Ucayali  Urbano  26.0  De 25 a 29 años de edad
38170   Ucayali   Ucayali  Urbano  16.0  De 15 a 19 años de edad

[12236 rows x 5 columns]

In [27]:
# Se encuentran 12,236 mujeres entre 15 y 30 años que viven en áreas urbanas

In [28]:
# Para validar esta información, contamos la cantidad de filas que tiene la cabecera "V013": Edad actual por grupos de 5 años"
  # sin haber realizado las funciones condicionales
    
dfx[["V013","V012"]].value_counts()

V013                     V012
De 25 a 29 años de edad  26.0    1239
De 12 a 14 años de edad  12.0    1228
                         14.0    1203
                         13.0    1202
De 25 a 29 años de edad  27.0    1200
De 30 a 34 años de edad  30.0    1183
                         31.0    1177
                         32.0    1175
                         34.0    1174
De 25 a 29 años de edad  25.0    1154
De 20 a 24 años de edad  24.0    1152
De 25 a 29 años de edad  28.0    1145
De 20 a 24 años de edad  23.0    1142
De 30 a 34 años de edad  33.0    1099
De 25 a 29 años de edad  29.0    1098
De 20 a 24 años de edad  22.0    1093
De 15 a 19 años de edad  15.0    1074
De 35 a 39 años de edad  36.0    1032
                         35.0    1029
                         37.0    1021
De 20 a 24 años de edad  20.0     999
De 15 a 19 años de edad  16.0     990
De 20 a 24 años de edad  21.0     964
De 35 a 39 años de edad  38.0     944
                         39.0     925
De 15 a 19 años de e

In [29]:
# Luego realizamos el mismo proceso para contar las filas filtradas y nos damos cuenta que la suma
 # corresponde a 12,236
    
Lugar_r[["V013","V012"]].value_counts()

V013                     V012
De 25 a 29 años de edad  26.0    936
De 30 a 34 años de edad  30.0    909
De 25 a 29 años de edad  27.0    886
                         25.0    844
                         28.0    844
De 20 a 24 años de edad  24.0    841
                         23.0    833
De 25 a 29 años de edad  29.0    796
De 20 a 24 años de edad  22.0    779
De 15 a 19 años de edad  15.0    721
De 20 a 24 años de edad  20.0    712
                         21.0    699
De 15 a 19 años de edad  19.0    638
                         16.0    624
                         18.0    595
                         17.0    579
dtype: int64

In [30]:
# 1.4.4 Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.
# Genera una nueva columna con el mes de nacimiento. Solo usa las tres primeras letras. Usa los nombres en inglés de los meses.

In [19]:
# Para poder realizar esta pregunta, se requiere los datos de la cabecera "V009": Mes de nacimiento de la entrevistada
 # y conocer el tipo de valor que tiene. Este caso Float

In [20]:
dfx.info("V009")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38335 entries, 0 to 38334
Data columns (total 105 columns):
 #    Column        Dtype   
---   ------        -----   
 0    ID1           float64 
 1    HHID          object  
 2    CASEID        object  
 3    V001          float64 
 4    V002          float64 
 5    V003          float64 
 6    V004          float64 
 7    V007          float64 
 8    V008          float64 
 9    V009          float64 
 10   V010          float64 
 11   V011          float64 
 12   V012          float64 
 13   V013          category
 14   V014          category
 15   V015          category
 16   V017          float64 
 17   V018          category
 18   V019          category
 19   V019A         float64 
 20   V020          category
 21   V021          float64 
 22   V023          category
 23   V024          category
 24   V025          category
 25   V026          category
 26   V027          float64 
 27   V028          float64 
 28   V029          

In [21]:
# Verificamos si existen los 12 meses del año

dfx["V009"].unique().tolist()

[4.0, 1.0, 6.0, 3.0, 5.0, 11.0, nan, 9.0, 8.0, 12.0, 10.0, 7.0, 2.0]

In [22]:
# Se realiza la creación de una nueva columna, remplazando los valos a través de la función Replace

dfx["nombre_mes"] = dfx["V009"].replace({
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
})
dfx

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_5  QD333_6  UBIGEO   V022  \
0         1.0  2019.0  1434.0   4.0  ...       No       No  010101    3.0   
1         1.0  2019.0  1434.0   1.0  ...       No       No  010101    3.0   
2         1.0  2019.0  1434.0   6.0  ...       No       No  010101    3.0   
3         1.0  2019.0  1434.0   3.0  ...       No       No  010101    3.0   
4         1.0  2019.0  1434.0   5.0  ...       No       No  010101    3.0   
...       ...     ...     ...   ...  ...      ...      ...     ...    ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No  250401  249.0   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No  250401  249.0   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No  250401  249.0   

           V005          V190      V191  \
0      154803.0          Rico  1.234450   
1      154803.0          Rico  1.234450   
2      154803.0          Rico  1.295611   
3      154803.0          Rico  1.295611   
4      154803.0        Pobrer -0.256431   
...         ...           ...       ...   
38330  244995.0  El más pobre -1.750187   
38331  244995.0  El más pobre -1.676861   
38332  459792.0  El más pobre -1.585333   
38333  459792.0  El más pobre -1.650159   
38334  244995.0  El más pobre -1.644720   

                                        mujeres12a49 NCONGLOME  nombre_mes  
0                    Mujeres de 15 a 49 años de edad    7065.0         Apr  
1      Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0         Jan  
2                    Mujeres de 15 a 49 años de edad    7065.0         Jun  
3                    Mujeres de 15 a 49 años de edad    7065.0         Mar  
4                    Mujeres de 15 a 49 años de edad    7065.0         May  
...                                              ...       ...         ...  
38330                Mujeres de 15 a 49 años de edad   15783.0         Dec  
38331                Mujeres de 15 a 49 años de edad   15783.0         Jun  
38332                Mujeres de 15 a 49 años de edad   15783.0         Jul  
38333                Mujeres de 15 a 49 años de edad   15783.0         Dec  
38334                Mujeres de 15 a 49 años de edad   15783.0         Oct  

[38335 rows x 106 columns]

In [24]:
dfx[["V009","nombre_mes"]].value_counts()

V009  nombre_mes
3.0   Mar           3233
9.0   Sep           3233
5.0   May           3208
7.0   Jul           3190
8.0   Aug           3184
12.0  Dec           3082
6.0   Jun           3081
1.0   Jan           3056
11.0  Nov           3001
10.0  Oct           2970
4.0   Apr           2938
2.0   Feb           2746
dtype: int64